import { useEffect } from 'react';
import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { createClient } from '../prismic-config';
import { asText } from '@prismicio/helpers';

export async function getStaticProps(context: NextPageContext) {
  const { previewData } = context;

  const client = createClient();
  if (previewData?.ref) {
    client.queryContentFromRef(previewData.ref);
  }

  const home = await client.getByUID('page', 'home');

  return {
    props: {
      home,
    },
  };
}

const Home: NextPage = (props) => {
  useEffect(() => {
    if (window) {
      window.addEventListener('prismicPreviewUpdate', async (event) => {
        // Prevent the toolbar from reloading the page.
        event.preventDefault();

        // Update the preview cookie.
        await fetch(`/api/preview?token=${event.detail.ref}`);

        // Reload the page with the updated token.
        window.location.reload();
      });
    }
  });

  console.log('props', props.home.data.title);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script
          async
          defer
          src={
            'https://static.cdn.prismic.io/prismic.js?new=true&repo=smashing-mag-nick-1'
          }></script>
      </Head>

      <main className={styles.main}>
        {props.home?.data.title && <h1>{asText(props.home.data.title)}</h1>}

        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
