// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string,
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
			TSubRelationship["customtypes"],
			TLang
		>;
	} & { // Group
		[TGroup in Extract<
			TRelationship["fields"][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
			infer TGroupData
		>
			? prismic.GroupField<
					PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
				>
			: never;
	} & { // Other fields
		[TFieldKey in Extract<
			TRelationship["fields"][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>["id"]]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>["id"]];

/** Content for Image Test documents */
interface ImageTestDocumentData {
	/**
	 * Empty field in _Image Test_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_test.empty
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	empty: prismic.ImageField<never>;

	/**
	 * Filled field in _Image Test_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_test.filled
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	filled: prismic.ImageField<never>;

	/**
	 * With Alt Text field in _Image Test_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_test.with_alt_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	with_alt_text: prismic.ImageField<never>;

	/**
	 * Without Alt Text field in _Image Test_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_test.without_alt_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	without_alt_text: prismic.ImageField<never>;

	/**
	 * With Crop field in _Image Test_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_test.with_crop
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	with_crop: prismic.ImageField<never>;
}

/**
 * Image Test document from Prismic
 *
 * - **API ID**: `image_test`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageTestDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<ImageTestDocumentData>,
		"image_test",
		Lang
	>;

/** Content for Link Test documents */
interface LinkTestDocumentData {
	/**
	 * Empty field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.empty
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	empty: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Internal Web field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.internal_web
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	internal_web: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>;

	/**
	 * External Web field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.external_web
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	external_web: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>;

	/**
	 * External Web With Target field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.external_web_with_target
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	external_web_with_target: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>;

	/**
	 * Document field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.document
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	document: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>;

	/**
	 * Media field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.media
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	media: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * With Text field in _Link Test_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: link_test.with_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	with_text: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>;
}

/**
 * Link Test document from Prismic
 *
 * - **API ID**: `link_test`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkTestDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<LinkTestDocumentData>,
		"link_test",
		Lang
	>;

/** Content for Page documents */
interface PageDocumentData {
	/**
	 * Payload field in _Page_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: page.payload
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	payload: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/** Content for Rich Text Test documents */
interface RichTextTestDocumentData {
	/**
	 * Hyperlink Internal field in _Rich Text Test_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: rich_text_test.hyperlink_internal
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	hyperlink_internal: prismic.RichTextField;

	/**
	 * Hyperlink External field in _Rich Text Test_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: rich_text_test.hyperlink_external
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	hyperlink_external: prismic.RichTextField;
}

/**
 * Rich Text Test document from Prismic
 *
 * - **API ID**: `rich_text_test`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RichTextTestDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<RichTextTestDocumentData>,
		"rich_text_test",
		Lang
	>;

export type AllDocumentTypes =
	| ImageTestDocument
	| LinkTestDocument
	| PageDocument
	| RichTextTestDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ImageTestDocument,
			ImageTestDocumentData,
			LinkTestDocument,
			LinkTestDocumentData,
			PageDocument,
			PageDocumentData,
			RichTextTestDocument,
			RichTextTestDocumentData,
			AllDocumentTypes,
		};
	}
}
